version: "3.9"
services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123

  mysql-db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin-ui:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: root123